In [ ]:
a=10
b=20
c=a+b
print(c)


30


Arithmatic operator

Logical **operator**

In [ ]:
a=2
b=1
c= a and b
print(c)

1


In [ ]:
a=10
b=20
print(a>12 or  b>15)


True


In [ ]:
a=10
b=20
print(not(a>11 and b>25))
a=10
b=20
print(a>8 and not(b>25))

True
True


END

Comparision Operator

In [ ]:
a=10
b=20
print(a>b)
print(b>a)
print(b>=a)
print(a<=b)
print(a==b)

False
True
True
True
False


assignment operator

In [ ]:
a=10
b=20
c = a+b
c += 10
print(c)
a=10
b=20
c = b-a
c -= 10
print(c)

40
0


prime number

In [ ]:
num=int(input("enter the enumber"))
count = 0
for i in range(1,num+1):
  if (num % i == 0):
    count += 1
if(count==2):
  print("prime")
else:
  print("not prime")

enter the enumber8
not prime


Factorial of a Number

In [ ]:
num = int(input("enter num"))
fact=1
for i in range(1,num+1):
 fact = fact * i
print(fact)


enter num5
120


reverse of a string

In [ ]:
s=input("enter the string")
print(s[::-1])



enter the stringyugendhar
rahdneguy


reverse of number


In [ ]:
num=int(input("enter the number"))
rev = 0;
while num > 0:
  rem = num % 10
  rev = rev * 10 + rem
  num = num //10
print (rev)


enter the number54321
12345


palindrome or not

In [ ]:
s = input("enter the n")
if(s==(s[::-1])):
  print("palindrome")
else:
  print("not palindrome")



enter the n1235
not palindrome


Armstrong number

In [ ]:
num = int(input("enter the number"))
temp = num
total = 0
l=len(str(num))
while (num > 0):
  digit = num % 10
  total += digit ** l
  num = num //10
if (total == temp):
  print("armstrong")
else:
  print("not armstrong")


enter the number153
armstrong


Fibonacci series

In [ ]:
num = int(input("enter the number"))
a = 0
b = 1
for i in range(1,num+1):
  print(a)
  c=a+b
  a=b
  b=c


enter the number5
0
1
1
2
3


maximum number

In [ ]:
a = [10,40,20,25,15]
maximum = a[0]

for i in a:
  if ( i > maximum):
    maximum = i
print(maximum)


40


In [ ]:
a = [10,40,20,25,15]
print(max(a))

40


Swapping of numbers

In [ ]:
a=10
b=20
a,b = b,a
print(a,b)

20 10


List

In [ ]:
stud=["yugendhar","task","hyderabad"]
stud.insert(1,"hhhh")
print(stud)

['yugendhar', 'hhhh', 'task', 'hyderabad']


tuple

In [ ]:
stud=["yugendhar","task","hyderabad"]
stud.append("hhhh")
print(stud)
github
drive
new folder
new colab file

['yugendhar', 'task', 'hyderabad', 'hhhh']


Mini project

In [ ]:
stud_name = input("enter the name")
stud_age = int(input("enter the age"))
sub_no = int(input("enter the subject name"))
sub = set()
for i in range(sub_no):
  sub_name = input("enter the name of subject {i+1}:")
  sub.add(sub_name)
  print("enter the subject name :" sub)
  sub_marks = {}
  for subject in sub():
    marks = int(input("enter the marks"))
    sub_marks[subject] = marks
  print("subject wise marks : {sub_marks}")
  student_name_list = [stud_name]
  student_info_tuple = (stud_name,stud_age)
 print(f"\nStored Data:")
 print(f"Student Name (List): {student_names_list}")
 print(f"Student Info (Tuple): {student_info_tuple}")
 print(f"Subjects (Set): {subjects}")
 print(f"Subject Marks (Dictionary): {subject_marks}")
 print("\n--- Student Report Card ---")
print(f"Name: {student_info_tuple[0]}")
print(f"Age: {student_info_tuple[1]}")
print("Subjects & Marks:")

total_marks = 0
for subject, marks in subject_marks.items():
  print(f"  - {subject}: {marks}")
  total_marks += marks

# Calculate average marks
num_subjects_recorded = len(subject_marks)
if num_subjects_recorded > 0:
  average_marks = total_marks / num_subjects_recorded
else:
  average_marks = 0 # Handle case with no subjects/marks

print(f"Total Marks: {total_marks}")
print(f"Average Marks: {average_marks:.2f}")
print("-------------------------")


SyntaxError: invalid syntax (1395691765.py, line 7)

### Student Report Card Program

In [ ]:
# 1. Get student name and age
student_name = input("Enter student name: ")
student_age = int(input("Enter student age: "))

In [ ]:
# 2. Get number of subjects and subject names
num_subjects = int(input("Enter the number of subjects: "))
subjects = set()
for i in range(num_subjects):
  subject_name = input(f"Enter name for subject {i+1}: ")
  subjects.add(subject_name)

print(f"Subjects entered: {subjects}")

In [ ]:
# 3. Get subject-wise marks
subject_marks = {}
for subject in subjects:
  marks = float(input(f"Enter marks for {subject}: "))
  subject_marks[subject] = marks

print(f"Subject-wise marks: {subject_marks}")

In [ ]:
# 4. Store data in specified data structures

# Name in a list
student_names_list = [student_name]

# Subjects in a set (already handled in previous step)
# subjects_set = subjects

# Student info in a tuple
student_info_tuple = (student_name, student_age)

# Marks in a dictionary (already handled in previous step)
# subject_marks_dict = subject_marks

print(f"\nStored Data:")
print(f"Student Name (List): {student_names_list}")
print(f"Student Info (Tuple): {student_info_tuple}")
print(f"Subjects (Set): {subjects}")
print(f"Subject Marks (Dictionary): {subject_marks}")

In [ ]:
# 5. Print a report card

print("\n--- Student Report Card ---")
print(f"Name: {student_info_tuple[0]}")
print(f"Age: {student_info_tuple[1]}")
print("Subjects & Marks:")

total_marks = 0
for subject, marks in subject_marks.items():
  print(f"  - {subject}: {marks}")
  total_marks += marks

# Calculate average marks
num_subjects_recorded = len(subject_marks)
if num_subjects_recorded > 0:
  average_marks = total_marks / num_subjects_recorded
else:
  average_marks = 0 # Handle case with no subjects/marks

print(f"Total Marks: {total_marks}")
print(f"Average Marks: {average_marks:.2f}")
print("-------------------------")

NUMPY

create an array of containing 1-20 using inbuilt function

In [ ]:
import numpy as np
np.array(range(1,20))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

create an array of all zeroes with 10 elements and convert it into matrix

In [ ]:
import numpy as np
matrix=np.zeros((1,10))
matrix.reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

create an array containaing even numbers from 2 to 20

In [ ]:
import numpy as np
np.array(range(2,21,2))

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

create an array and find no of diamensions, shape,size,datatype and multiply every element by 2

create 1d array and find sum,mean,max,?

PANDAS

In [ ]:
import pandas as pd
s1=pd.Series([1,2,3,4])
print(s1.describe())


count    4.000000
mean     2.500000
std      1.290994
min      1.000000
25%      1.750000
50%      2.500000
75%      3.250000
max      4.000000
dtype: float64


In [ ]:
import pandas as pd
s1=pd.Series([1,2,3,4])
print(s1.mean())
print(s1.std())
print(s1.max())
print(s1.min())
print(s1.sum())

2.5
1.2909944487358056
4
1
10


In [ ]:
import pandas as pd
s1=pd.Series([1,2,3,4])
print(s1.mean())
print(s1.std())
print(s1.max())
print(s1.min())
print(s1.sum())